import type { Metadata } from "next";
import { ClerkProvider, UserButton } from "@clerk/nextjs";

import { MainNav } from "./_components/main-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <div className="flex-col md:flex">
        <div className="border-b">
          <div className="flex h-16 items-center px-4">
            <MainNav className="mx-6" />

            <div className="ml-auto flex items-center space-x-4">
              <UserButton
                afterSignOutUrl="/"
              />
            </div>
          </div>
        </div>

        <div className="flex-1 space-y-4 p-8 pt-6">{children}</div>
      </div>
    </ClerkProvider>
  );
}